### ISSUE TITLE
Release new version 

### ISSUE THREAD

**Issue by y-yagi** [seattlerb/minitest-server#2]
Currently released version does not work with latest Minitest.  
This means that `minitest-bisect` dependent on `minitest-server` also does not work.
I want new version that includes https://github.com/seattlerb/minitest-server/commit/4c5827fdd2318603c69eca32bba39d91642e7bf8. 

Please consider this. Thanks.

**Comment by yahonda** [comment]
Let me add some more background for this request since this request must have been opened since rails/rails#31893

Now Rails framework unit test uses Minitest 5.11.1, which runs tests in random order. Still, there are some order dependent failures reported such as rails/rails#31905. minitest-bisect helps a lot to find this kind of order-dependent failures, but current Minitest 5.11.1 gets undefined method errors fixed by https://github.com/seattlerb/minitest-server/commit/4c5827fdd2318603c69eca32bba39d91642e7bf8

It would be really helpful if the newer version of minitest-server including this fix.

Thank you.

**Comment by zenspider** [comment]
I will try to get this fixed today.

**Comment by y-yagi** [comment]
It seems that a new version has been released. Thanks!
